#ifndef _TEST_CONFIG_H_
#define _TEST_CONFIG_H_

#include "catch.hpp"
#include "settings.h"

#define CAN_MESSAGE_AVAIL_TEST 5
#define DEFAULT_START_TIME_MILLIS 5000
#define DEFAULT_STALE_TIME_MILLIS DEFAULT_START_TIME_MILLIS + STALE_INTERVAL

#endif